'use strict';

module.exports = {
  write: true,
  prefix: '^',
  plugin: 'autod-egg',
  test: [
    'test',
    'benchmark',
  ],
  dep: [
    'egg',
    'egg-scripts',
	  'nuxt',
    'egg-sequelize',
    'egg-passport',
    'egg-cors',
    'mysql2',
    'pg',
    'node-rsa',
    'moment',
    'change-case',
    'joi',
    'bcrypt',
    'js-base64',
    'mint-ui',
  ],
  devdep: [
    'babel-eslint',
    'egg-ci',
    'egg-bin',
    'egg-mock',
    'autod',
    'autod-egg',
    'eslint',
    'cross-env',
    'eslint-config-egg',
	  'eslint-config-standard',
    'eslint-loader',
    'eslint-plugin-html',
    'eslint-plugin-import',
    'eslint-plugin-node',
    'eslint-plugin-promise',
    'eslint-plugin-standard',
    'eslint-plugin-vue',
    'less',
    'less-loader',
    'node-less',
    'sass',
    'jsdoc',
    'sass-loader',
    'node-sass',
    'webstorm-disable-index',
  ],
  semver:[
    'pg@6.4.2',
  ],
  exclude: [
    './test/fixtures',
    './dist',
    './.nuxt',
  ],
};
